# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160113_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='password',
        ),
    ]
