# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_username_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='password',
            field=models.CharField(default='this is a default password', max_length=30),
        ),
    ]
