# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_username_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID_email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
